//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainWindow {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ButtonText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ButtonText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainWindow.ButtonText", typeof(ButtonText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Cliping Toolbox.
        /// </summary>
        internal static string HideClipingToolbox {
            get {
                return ResourceManager.GetString("HideClipingToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide PlaneX.
        /// </summary>
        internal static string HidePlaneX {
            get {
                return ResourceManager.GetString("HidePlaneX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide PlaneY.
        /// </summary>
        internal static string HidePlaneY {
            get {
                return ResourceManager.GetString("HidePlaneY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide PlaneZ.
        /// </summary>
        internal static string HidePlaneZ {
            get {
                return ResourceManager.GetString("HidePlaneZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Cliping Toolbox.
        /// </summary>
        internal static string ShowClipingToolbox {
            get {
                return ResourceManager.GetString("ShowClipingToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show PlaneX.
        /// </summary>
        internal static string ShowPlaneX {
            get {
                return ResourceManager.GetString("ShowPlaneX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show PlaneY.
        /// </summary>
        internal static string ShowPlaneY {
            get {
                return ResourceManager.GetString("ShowPlaneY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show PlaneZ.
        /// </summary>
        internal static string ShowPlaneZ {
            get {
                return ResourceManager.GetString("ShowPlaneZ", resourceCulture);
            }
        }
    }
}
