//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainWindow.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainWindow.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;CsaMscData&gt;&lt;MscHeader Version=&quot;SV10&quot;/&gt;&lt;Cap3dSettingsVrt&gt;&lt;Cap3dSettings&gt;&lt;SettingsVersion&gt;1.0&lt;/SettingsVersion&gt;
        ///&lt;SettingsType&gt;Cap3dSettingsTypeVrt&lt;/SettingsType&gt;
        ///&lt;SettingsName&gt;Abd_shaded_A.bmp&lt;/SettingsName&gt;
        ///&lt;SettingsProperties&gt;&lt;Properties&gt;&lt;Head&gt;&lt;Value&gt;&lt;First&gt;ViewType&lt;/First&gt;
        ///&lt;Second&gt;External&lt;/Second&gt;
        ///&lt;/Value&gt;
        ///&lt;Next&gt;&lt;Value&gt;&lt;First&gt;Modality&lt;/First&gt;
        ///&lt;Second&gt;1.2.840.10008.5.1.4.1.1.2&lt;/Second&gt;
        ///&lt;/Value&gt;
        ///&lt;/Next&gt;
        ///&lt;/Head&gt;
        ///&lt;/Properties&gt;
        ///&lt;/SettingsProperties&gt;
        ///&lt;/Cap3 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Abd_shaded_A {
            get {
                return ResourceManager.GetString("Abd_shaded_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;CsaMscData&gt;&lt;MscHeader Version=&quot;SV10&quot;/&gt;&lt;Cap3dSettingsVrt&gt;&lt;Cap3dSettings&gt;&lt;SettingsVersion&gt;1.0&lt;/SettingsVersion&gt;
        ///&lt;SettingsType&gt;Cap3dSettingsTypeVrt&lt;/SettingsType&gt;
        ///&lt;SettingsName&gt;Abd_shaded_B&lt;/SettingsName&gt;
        ///&lt;SettingsProperties&gt;&lt;Properties&gt;&lt;Head&gt;&lt;Value&gt;&lt;First&gt;ViewType&lt;/First&gt;
        ///&lt;Second&gt;External&lt;/Second&gt;
        ///&lt;/Value&gt;
        ///&lt;Next&gt;&lt;Value&gt;&lt;First&gt;Modality&lt;/First&gt;
        ///&lt;Second&gt;1.2.840.10008.5.1.4.1.1.2&lt;/Second&gt;
        ///&lt;/Value&gt;
        ///&lt;/Next&gt;
        ///&lt;/Head&gt;
        ///&lt;/Properties&gt;
        ///&lt;/SettingsProperties&gt;
        ///&lt;/Cap3dSet [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Abd_shaded_B {
            get {
                return ResourceManager.GetString("Abd_shaded_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;CsaMscData&gt;&lt;MscHeader Version=&quot;SV10&quot;/&gt;&lt;Cap3dSettingsVrt&gt;&lt;Cap3dSettings&gt;&lt;SettingsVersion&gt;1.0&lt;/SettingsVersion&gt;
        ///&lt;SettingsType&gt;Cap3dSettingsTypeVrt&lt;/SettingsType&gt;
        ///&lt;SettingsName&gt;Carotid_sha_A.bmp&lt;/SettingsName&gt;
        ///&lt;SettingsProperties&gt;&lt;Properties&gt;&lt;Head&gt;&lt;Value&gt;&lt;First&gt;ViewType&lt;/First&gt;
        ///&lt;Second&gt;External&lt;/Second&gt;
        ///&lt;/Value&gt;
        ///&lt;Next&gt;&lt;Value&gt;&lt;First&gt;Modality&lt;/First&gt;
        ///&lt;Second&gt;1.2.840.10008.5.1.4.1.1.2&lt;/Second&gt;
        ///&lt;/Value&gt;
        ///&lt;/Next&gt;
        ///&lt;/Head&gt;
        ///&lt;/Properties&gt;
        ///&lt;/SettingsProperties&gt;
        ///&lt;/Cap [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Carotid_sha_A {
            get {
                return ResourceManager.GetString("Carotid_sha_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;CsaMscData&gt;&lt;MscHeader Version=&quot;SV10&quot;/&gt;&lt;Cap3dSettingsVrt&gt;&lt;Cap3dSettings&gt;&lt;SettingsVersion&gt;1.0&lt;/SettingsVersion&gt;
        ///&lt;SettingsType&gt;Cap3dSettingsTypeVrt&lt;/SettingsType&gt;
        ///&lt;SettingsName&gt;Carotid_Stent_A&lt;/SettingsName&gt;
        ///&lt;SettingsProperties&gt;&lt;Properties&gt;&lt;Head&gt;&lt;Value&gt;&lt;First&gt;ViewType&lt;/First&gt;
        ///&lt;Second&gt;External&lt;/Second&gt;
        ///&lt;/Value&gt;
        ///&lt;Next&gt;&lt;Value&gt;&lt;First&gt;Modality&lt;/First&gt;
        ///&lt;Second&gt;1.2.840.10008.5.1.4.1.1.12.1&lt;/Second&gt;
        ///&lt;/Value&gt;
        ///&lt;/Next&gt;
        ///&lt;/Head&gt;
        ///&lt;/Properties&gt;
        ///&lt;/SettingsProperties&gt;
        ///&lt;/Ca [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Carotid_Stent_A {
            get {
                return ResourceManager.GetString("Carotid_Stent_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;CsaMscData&gt;&lt;MscHeader Version=&quot;SV10&quot;/&gt;&lt;Cap3dSettingsVrt&gt;&lt;Cap3dSettings&gt;&lt;SettingsVersion&gt;1.0&lt;/SettingsVersion&gt;
        ///&lt;SettingsType&gt;Cap3dSettingsTypeVrt&lt;/SettingsType&gt;
        ///&lt;SettingsName&gt;Colonography&lt;/SettingsName&gt;
        ///&lt;SettingsProperties&gt;&lt;Properties&gt;&lt;Head&gt;&lt;Value&gt;&lt;First&gt;Modality&lt;/First&gt;
        ///&lt;Second&gt;1.2.840.10008.5.1.4.1.1.2&lt;/Second&gt;
        ///&lt;/Value&gt;
        ///&lt;Next&gt;&lt;Value&gt;&lt;First&gt;ViewType&lt;/First&gt;
        ///&lt;Second&gt;External&lt;/Second&gt;
        ///&lt;/Value&gt;
        ///&lt;/Next&gt;
        ///&lt;/Head&gt;
        ///&lt;/Properties&gt;
        ///&lt;/SettingsProperties&gt;
        ///&lt;/Cap3dSettings&gt;
        ///&lt;Classi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Colonography {
            get {
                return ResourceManager.GetString("Colonography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;CsaMscData&gt;&lt;MscHeader Version=&quot;SV10&quot;/&gt;&lt;Cap3dSettingsVrt&gt;&lt;Cap3dSettings&gt;&lt;SettingsVersion&gt;1.0&lt;/SettingsVersion&gt;
        ///&lt;SettingsType&gt;Cap3dSettingsTypeVrt&lt;/SettingsType&gt;
        ///&lt;SettingsName&gt;CT Angio Routine&lt;/SettingsName&gt;
        ///&lt;SettingsProperties&gt;&lt;Properties&gt;&lt;Head&gt;&lt;Value&gt;&lt;First&gt;Modality&lt;/First&gt;
        ///&lt;Second&gt;1.2.840.10008.5.1.4.1.1.2&lt;/Second&gt;
        ///&lt;/Value&gt;
        ///&lt;Next&gt;&lt;Value&gt;&lt;First&gt;ViewType&lt;/First&gt;
        ///&lt;Second&gt;External&lt;/Second&gt;
        ///&lt;/Value&gt;
        ///&lt;/Next&gt;
        ///&lt;/Head&gt;
        ///&lt;/Properties&gt;
        ///&lt;/SettingsProperties&gt;
        ///&lt;/Cap3dSettings&gt;
        ///&lt;Cl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CT_Angio_Routine {
            get {
                return ResourceManager.GetString("CT_Angio_Routine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;CsaMscData&gt;&lt;MscHeader Version=&quot;SV10&quot;/&gt;&lt;Cap3dSettingsVrt&gt;&lt;Cap3dSettings&gt;&lt;SettingsVersion&gt;1.0&lt;/SettingsVersion&gt;
        ///&lt;SettingsType&gt;Cap3dSettingsTypeVrt&lt;/SettingsType&gt;
        ///&lt;SettingsName&gt;CT Angio Shaded&lt;/SettingsName&gt;
        ///&lt;SettingsProperties&gt;&lt;Properties&gt;&lt;Head&gt;&lt;Value&gt;&lt;First&gt;Modality&lt;/First&gt;
        ///&lt;Second&gt;1.2.840.10008.5.1.4.1.1.2&lt;/Second&gt;
        ///&lt;/Value&gt;
        ///&lt;Next&gt;&lt;Value&gt;&lt;First&gt;ViewType&lt;/First&gt;
        ///&lt;Second&gt;External&lt;/Second&gt;
        ///&lt;/Value&gt;
        ///&lt;/Next&gt;
        ///&lt;/Head&gt;
        ///&lt;/Properties&gt;
        ///&lt;/SettingsProperties&gt;
        ///&lt;/Cap3dSettings&gt;
        ///&lt;Cla [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CT_Angio_Shaded {
            get {
                return ResourceManager.GetString("CT_Angio_Shaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;CsaMscData&gt;&lt;MscHeader Version=&quot;SV10&quot;/&gt;&lt;Cap3dSettingsVrt&gt;&lt;Cap3dSettings&gt;&lt;SettingsVersion&gt;1.0&lt;/SettingsVersion&gt;
        ///&lt;SettingsType&gt;Cap3dSettingsTypeVrt&lt;/SettingsType&gt;
        ///&lt;SettingsName&gt;CT Carotis Coloured Green&lt;/SettingsName&gt;
        ///&lt;SettingsProperties&gt;&lt;Properties&gt;&lt;Head&gt;&lt;Value&gt;&lt;First&gt;Modality&lt;/First&gt;
        ///&lt;Second&gt;1.2.840.10008.5.1.4.1.1.2&lt;/Second&gt;
        ///&lt;/Value&gt;
        ///&lt;Next&gt;&lt;Value&gt;&lt;First&gt;ViewType&lt;/First&gt;
        ///&lt;Second&gt;External&lt;/Second&gt;
        ///&lt;/Value&gt;
        ///&lt;/Next&gt;
        ///&lt;/Head&gt;
        ///&lt;/Properties&gt;
        ///&lt;/SettingsProperties&gt;
        ///&lt;/Cap3dSett [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CT_Carotis_Coloured_Green {
            get {
                return ResourceManager.GetString("CT_Carotis_Coloured_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;CsaMscData&gt;&lt;MscHeader Version=&quot;SV10&quot;/&gt;&lt;Cap3dSettingsVrt&gt;&lt;Cap3dSettings&gt;&lt;SettingsVersion&gt;1.0&lt;/SettingsVersion&gt;
        ///&lt;SettingsType&gt;Cap3dSettingsTypeVrt&lt;/SettingsType&gt;
        ///&lt;SettingsName&gt;CT Coronary Std&lt;/SettingsName&gt;
        ///&lt;SettingsProperties&gt;&lt;Properties&gt;&lt;Head&gt;&lt;Value&gt;&lt;First&gt;Modality&lt;/First&gt;
        ///&lt;Second&gt;1.2.840.10008.5.1.4.1.1.4&lt;/Second&gt;
        ///&lt;/Value&gt;
        ///&lt;Next&gt;&lt;Value&gt;&lt;First&gt;ViewType&lt;/First&gt;
        ///&lt;Second&gt;External&lt;/Second&gt;
        ///&lt;/Value&gt;
        ///&lt;/Next&gt;
        ///&lt;/Head&gt;
        ///&lt;/Properties&gt;
        ///&lt;/SettingsProperties&gt;
        ///&lt;/Cap3dSettings&gt;
        ///&lt;Cla [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CT_Coronary_Std_01 {
            get {
                return ResourceManager.GetString("CT_Coronary_Std_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;CsaMscData&gt;&lt;MscHeader Version=&quot;SV10&quot;/&gt;&lt;Cap3dSettingsVrt&gt;&lt;Cap3dSettings&gt;&lt;SettingsVersion&gt;1.0&lt;/SettingsVersion&gt;
        ///&lt;SettingsType&gt;Cap3dSettingsTypeVrt&lt;/SettingsType&gt;
        ///&lt;SettingsName&gt;CT Kidney&lt;/SettingsName&gt;
        ///&lt;SettingsProperties&gt;&lt;Properties&gt;&lt;Head&gt;&lt;Value&gt;&lt;First&gt;Modality&lt;/First&gt;
        ///&lt;Second&gt;1.2.840.10008.5.1.4.1.1.2&lt;/Second&gt;
        ///&lt;/Value&gt;
        ///&lt;Next&gt;&lt;Value&gt;&lt;First&gt;ViewType&lt;/First&gt;
        ///&lt;Second&gt;External&lt;/Second&gt;
        ///&lt;/Value&gt;
        ///&lt;/Next&gt;
        ///&lt;/Head&gt;
        ///&lt;/Properties&gt;
        ///&lt;/SettingsProperties&gt;
        ///&lt;/Cap3dSettings&gt;
        ///&lt;Classific [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CT_Kidney {
            get {
                return ResourceManager.GetString("CT_Kidney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;CsaMscData&gt;&lt;MscHeader Version=&quot;SV10&quot;/&gt;&lt;Cap3dSettingsVrt&gt;&lt;Cap3dSettings&gt;&lt;SettingsVersion&gt;1.0&lt;/SettingsVersion&gt;
        ///&lt;SettingsType&gt;Cap3dSettingsTypeVrt&lt;/SettingsType&gt;
        ///&lt;SettingsName&gt;CT Thin Slice VRT Abd&lt;/SettingsName&gt;
        ///&lt;SettingsProperties&gt;&lt;Properties&gt;&lt;Head&gt;&lt;Value&gt;&lt;First&gt;Modality&lt;/First&gt;
        ///&lt;Second&gt;1.2.840.10008.5.1.4.1.1.128&lt;/Second&gt;
        ///&lt;/Value&gt;
        ///&lt;Next&gt;&lt;Value&gt;&lt;First&gt;ViewType&lt;/First&gt;
        ///&lt;Second&gt;External&lt;/Second&gt;
        ///&lt;/Value&gt;
        ///&lt;/Next&gt;
        ///&lt;/Head&gt;
        ///&lt;/Properties&gt;
        ///&lt;/SettingsProperties&gt;
        ///&lt;/Cap3dSettin [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CT_Thin_Slice_VRT_Abd_03 {
            get {
                return ResourceManager.GetString("CT_Thin_Slice_VRT_Abd_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;CsaMscData&gt;&lt;MscHeader Version=&quot;SV10&quot;/&gt;&lt;Cap3dSettingsVrt&gt;&lt;Cap3dSettings&gt;&lt;SettingsVersion&gt;1.0&lt;/SettingsVersion&gt;
        ///&lt;SettingsType&gt;Cap3dSettingsTypeVrt&lt;/SettingsType&gt;
        ///&lt;SettingsName&gt;Extremities&lt;/SettingsName&gt;
        ///&lt;SettingsProperties&gt;&lt;Properties&gt;&lt;Head&gt;&lt;Value&gt;&lt;First&gt;ViewType&lt;/First&gt;
        ///&lt;Second&gt;External&lt;/Second&gt;
        ///&lt;/Value&gt;
        ///&lt;Next&gt;&lt;Value&gt;&lt;First&gt;Modality&lt;/First&gt;
        ///&lt;Second&gt;1.2.840.10008.5.1.4.1.1.2&lt;/Second&gt;
        ///&lt;/Value&gt;
        ///&lt;/Next&gt;
        ///&lt;/Head&gt;
        ///&lt;/Properties&gt;
        ///&lt;/SettingsProperties&gt;
        ///&lt;/Cap3dSett [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Extremities {
            get {
                return ResourceManager.GetString("Extremities", resourceCulture);
            }
        }
    }
}
